const FETCH_REQUEST = 'watches/FETCH_REQUEST';
const FETCH_SUCCESS = 'watches/FETCH_SUCCESS';
const FETCH_ERROR = 'watches/FETCH_ERROR';

const HIT_FETCH_REQUEST = 'hit/FETCH_REQUEST';
const HIT_FETCH_SUCCESS = 'hit/FETCH_SUCCESS';
const HIT_FETCH_ERROR = 'hit/FETCH_ERROR';

export default {
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
  HIT_FETCH_REQUEST,
  HIT_FETCH_SUCCESS,
  HIT_FETCH_ERROR,
};
